// frontend/source/js/views/lost_password.jsx
(function() {
  "use strict"

  App.Views.LostPasswordPage = React.createClass({
    getInitialState: function() {
      return {
        email: null
      }
    },

    handleChange: function(name, event) {
      var h = {}
      h[name] = event.target.value
      this.setState(h)
    },

    render: function() {
      return (
        <div className="lostPassword">
          <header>
            <h1>The Pithy Reader</h1>
          </header>
          <form onSubmit={this.requestPasswordReset}>
            <dl>
              <dt>
                <label htmlFor="email">Email</label>
              </dt>
              <dd><input type="email" id="email" autofocus value={this.state.email} onChange={this.handleChange.bind(null, "email")} /></dd>
            </dl>

            <input type="submit" value="Reset Password" />
          </form>
        </div>
      );
    },

    requestPasswordReset: function(e) {
      e.preventDefault()
      var form = e.currentTarget
      conn.requestPasswordReset(this.state.email, {
        succeeded: this.onRequestPasswordResetSuccess,
        failed: function(_, response) { this.onRequestPasswordResetFailure(response.responseText) }.bind(this)
      })
    },

    onRequestPasswordResetSuccess: function(data) {
      alert("Please check your email for reset information")
    },

    onRequestPasswordResetFailure: function(response) {
      alert("Failure resetting password")
    }
  })
})()

// src/routes/(auth)/lostPassword/+page.svelte
<script>
	import { api } from '$lib/api.js';

	let email = '';

	async function requestPasswordReset() {
		try {
			await api.requestPasswordReset(email);
			alert('Please check your email for reset information');
		} catch (error) {
			alert('Failure resetting password');
		}
	}
</script>

<div class="lostPassword">
	<form on:submit|preventDefault={requestPasswordReset}>
		<dl>
			<dt>
				<label for="email">Email</label>
			</dt>
			<dd>
				<input type="email" id="email" autofocus bind:value={email} />
			</dd>
		</dl>

		<input type="submit" value="Reset Password" />
	</form>
</div>
