// frontend/source/js/views/feeds.jsx
(function() {
  "use strict"

  App.Views.FeedsPage = React.createClass({
    getInitialState: function() {
      return {
        feeds: [],
        url: ""
      }
    },

    componentDidMount: function() {
      this.fetch()
    },

    handleChange: function(name, event) {
      var h = {}
      h[name] = event.target.value
      this.setState(h)
    },

    fetch: function() {
      conn.getFeeds({
        succeeded: function(data) {
          this.setState({feeds: data})
        }.bind(this)
      })
    },

    render: function() {
      return (
        <div className="feeds">
          <App.Views.LoggedInHeader />

          <form className="subscribe" onSubmit={this.subscribe}>
            <dl>
              <dt>
                <label for="feed_url">Feed URL</label>
              </dt>
              <dd><input type="text" id="feed_url" value={this.state.url} onChange={this.handleChange.bind(null, "url")} /></dd>
            </dl>
            <input type="submit" value="Subscribe" />
          </form>

          <form className="import" onSubmit={this.import}>
            <dl>
              <dt>
                <label for="opml_file">OPML File</label>
              </dt>
              <dd><input type="file" name="file" id="opml_file" /></dd>
            </dl>
            <input type="submit" value="Import" />
            {' '}
            <a href={"/api/feeds.xml?session="+State.Session.id}>Export</a>
          </form>

          <ul>
            {
              this.state.feeds.map(function(feed, index) {
                return (
                  <li>
                    <div className="name"><a href={feed.url}>{feed.name}</a></div>
                    {(function() {
                      if(feed.last_publication_time) {
                        return (
                          <div className="meta">
                            Last published
                            {' '}
                            <time datetime={feed.last_publication_time.toISOString()}>{feed.last_publication_time.toTPRString()}</time>
                          </div>
                        )
                      }
                    })()}
                    {(function() {
                      if(feed.failure_count > 0) {
                        return (
                          <div className="error">{feed.last_failure}</div>
                        )
                      }
                    })()}
                    <div className="actions">
                      <a href="#" onClick={this.unsubscribe.bind(null, feed)}>Unsubscribe</a>
                    </div>
                  </li>
                )
              }.bind(this))
            }
          </ul>
        </div>
      );
    },

    subscribe: function(e) {
      e.preventDefault()

      conn.subscribe(this.state.url, {
        succeeded: function() {
          this.setState({"url": ""})
          this.fetch()
        }.bind(this)
      })
    },

    unsubscribe: function(feed, e) {
      e.preventDefault()
      if(confirm("Are you sure you want to unsubscribe from " + feed.name + "?")) {
        conn.deleteSubscription(feed.feed_id)
        this.fetch()
      }
    },

    import: function(e) {
      e.preventDefault()
      var fd = new FormData(e.target)

      conn.importOPML(fd, {
        succeeded: function() {
          this.fetch()
          alert("import success")
        }.bind(this)
      })
    }
  })
})()

// src/routes/(protected)/feeds/+page.svelte
<script>
	import { onMount } from 'svelte';
	import { api } from '$lib/api.js';
	import { session } from '$lib/session.js';
	import { toTPRString } from '$lib/utils/date.js';

	let feeds = [];
	let url = '';

	onMount(() => {
		fetchFeeds();
	});

	async function fetchFeeds() {
		try {
			feeds = await api.getFeeds();
		} catch (error) {
			console.error('Failed to fetch feeds', error);
		}
	}

	async function subscribe(e) {
		e.preventDefault();

		try {
			await api.subscribe(url);
			url = '';
			await fetchFeeds();
		} catch (error) {
			alert('Subscription failed');
		}
	}

	async function unsubscribe(feed, e) {
		e.preventDefault();
		if (confirm('Are you sure you want to unsubscribe from ' + feed.name + '?')) {
			await api.deleteSubscription(feed.feed_id);
			feeds = feeds.filter((f) => f !== feed);
		}
	}

	async function importOPML(e) {
		e.preventDefault();
		const formData = new FormData(e.target);

		try {
			await api.importOPML(formData);
			await fetchFeeds();
			alert('import success');
		} catch (error) {
			alert('Import failed');
		}
	}
</script>

<div class="feeds">
	<form class="subscribe" on:submit={subscribe}>
		<dl>
			<dt>
				<label for="feed_url">Feed URL</label>
			</dt>
			<dd>
				<input type="text" id="feed_url" bind:value={url} />
			</dd>
		</dl>
		<input type="submit" value="Subscribe" />
	</form>

	<form class="import" on:submit={importOPML}>
		<dl>
			<dt>
				<label for="opml_file">OPML File</label>
			</dt>
			<dd><input type="file" name="file" id="opml_file" /></dd>
		</dl>
		<input type="submit" value="Import" />
		{' '}
		<a href="/api/feeds.xml?session={$session.id}">Export</a>
	</form>

	<ul>
		{#each feeds as feed (feed.url)}
			<li>
				<div class="name"><a href={feed.url}>{feed.name}</a></div>
				{#if feed.last_publication_time}
					<div class="meta">
						Last published
						{' '}
						<time datetime={feed.last_publication_time.toISOString()}>
							{toTPRString(feed.last_publication_time)}
						</time>
					</div>
				{/if}
				{#if feed.failure_count > 0}
					<div class="error">{feed.last_failure}</div>
				{/if}
				<div class="actions">
					<a href="#" on:click={(e) => unsubscribe(feed, e)}>Unsubscribe</a>
				</div>
			</li>
		{/each}
	</ul>
</div>
