// frontend/source/js/views/login.jsx
(function() {
  "use strict"

  App.Views.LoginPage = React.createClass({
    getInitialState: function() {
      return {
        name: null,
        password: null
      }
    },

    handleChange: function(name, event) {
      var h = {}
      h[name] = event.target.value
      this.setState(h)
    },

    render: function() {
      return (
        <div className="login">
          <form onSubmit={this.login}>
            <dl>
              <dt>
                <label htmlFor="name">User name</label>
              </dt>
              <dd><input type="text" id="name" autofocus value={this.state.name} onChange={this.handleChange.bind(null, "name")} /></dd>

              <dt>
                <label htmlFor="password">Password</label>
              </dt>
              <dd><input type="password" id="password" value={this.state.password} onChange={this.handleChange.bind(null, "password")} /></dd>
            </dl>

            <input type="submit" value="Login" />
            {' '}
            <a href="#register" className="register">Create an account</a>
            {' '}
            <a href="#lostPassword" className="lostPassword">Lost password</a>
          </form>
        </div>
      );
    },

    login: function(e) {
      e.preventDefault()

      var credentials = {
        name: this.state.name,
        password: this.state.password
      }
      conn.login(credentials, {
        succeeded: this.onLoginSuccess,
        failed: function(_, response) { this.onLoginFailure(response.responseText) }.bind(this)
      })
    },

    onLoginSuccess: function(data) {
      State.Session = new App.Models.Session(data)
      State.Session.save()
      window.router.navigate('home')
    },

    onLoginFailure: function(response) {
      alert(response)
    }
  })
})()

// src/routes/(auth)/login/+page.svelte
<script>
	import { goto } from '$app/navigation';
	import { api } from '$lib/api.js';
	import { session } from '$lib/session.js';

	let username = '';
	let password = '';

	async function login() {
		try {
			const data = await api.login({ name: username, password });
			session.set({ id: data.sessionID, name: data.name });
			goto('/home');
		} catch (error) {
			alert(error.data || 'Login failed');
		}
	}
</script>

<div class="login">
	<form on:submit|preventDefault={login} autocomplete="off">
		<dl>
			<dt>
				<label for="username">User name</label>
			</dt>
			<dd>
				<input type="text" id="username" name="username" bind:value={username} />
			</dd>

			<dt>
				<label for="password">Password</label>
			</dt>
			<dd>
				<input type="password" id="password" name="password" bind:value={password} />
			</dd>
		</dl>

		<input type="submit" value="Login" />
		<a href="/register" class="register">Create an account</a>
		<a href="/lostPassword" class="lostPassword">Lost password</a>
	</form>
</div>
