// frontend/src/components/Header.jsx
import React from 'react'
import { Link, useNavigate } from 'react-router-dom'
import Session from '../session.js'
import {conn} from '../connection.js'

export default function Header() {
  const navigate = useNavigate()

  const logout = (e) => {
    e.preventDefault()
    conn.logout()
    Session.clear()
    navigate('/login')
  }

  const renderLoggedInNav = () => (
    <nav>
      <Link to="/home">Home</Link>
      {' '}
      <Link to="/archive">Archive</Link>
      {' '}
      <Link to="/feeds">Feeds</Link>
      {' '}
      <Link to="/account">Account</Link>
      {' '}
      <a href="#" onClick={logout}>Logout</a>
    </nav>
  )

  return (
    <header>
      <h1>The Pithy Reader</h1>
      {Session.isAuthenticated() ? renderLoggedInNav() : null}
    </header>
  )
}

// src/lib/components/Header.svelte
<script>
	import { goto } from '$app/navigation';
	import { session } from '$lib/session.js';
	import { api } from '$lib/api.js';

	async function logout(e) {
		e.preventDefault();
		await api.logout();
		session.clear();
		goto('/login');
	}
</script>

<header>
	<h1>The Pithy Reader</h1>
	{#if $session.id}
		<nav>
			<a href="/home">Home</a>
			{' '}
			<a href="/archive">Archive</a>
			{' '}
			<a href="/feeds">Feeds</a>
			{' '}
			<a href="/account">Account</a>
			{' '}
			<a href="/login" on:click={logout}>Logout</a>
		</nav>
	{/if}
</header>
